map_type: costmapi

obstacle_range: 2.5
raytrace_range: 4
cost_scaling_factor: 5 # Default



transform_tolerance: 0.2 # Default

# robot_radius: 0.
footprint : [[0.18, 0.17],[0.23,0.0],[0.18, -0.17],[-0.19, -0.17],[-0.19, 0.17]]
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
